Sprint 17
AndrewP-GH/Tracker pull request #6
Opened 2023-11-21 00:10 UTC by AndrewP-GH

2023-11-27 16:11 UTC, protos17 requested changes

2023-11-27 16:11 UTC, protos17 commented on Tracker/Domain/AnalyticsService.swift
> +    func report(event: String, params: [AnyHashable: Any]) {
Рекомендую указать event, screen и item указать в энамах и обращаться к кейсам этого энама, а не писать строкой, чтобы не ошибиться, например:

           enum Screen: String {
              case main
              ...
              }

2023-11-27 16:11 UTC, protos17 commented on Tracker/Resources/en.lproj/Localizable.strings
> +"trackers.filters" = "Filters";
Filters повторяется

2023-11-27 16:11 UTC, protos17 commented on Tracker/Resources/ru.lproj/Localizable.strings
> +"trackers.filters" = "Фильтры";
Тут тоже повторяется Фильтры

2023-11-27 16:11 UTC, protos17 commented on Tracker/UI/Categories/CategoriesViewController.swift
>  import Foundation
При импорте UIKit можно не импортировать Foundation, потому что первый содержит в себе второй

2023-11-27 16:11 UTC, protos17 commented on Tracker/UI/Common/EmptyResultPlaceholderView.swift
>  import Foundation
Можно не писать

2023-11-27 16:11 UTC, protos17 commented on Tracker/UI/Statistics/StatisticsViewController.swift
> +        // поэтому пока что я просто скрываю таблицу и показываю плейсхолдер :)
Необходимо реализовать подсчет количества выполненных трекеров. У тебя же реализован подсчет количества выполненных трекеров, отталкивайся от этого

2023-11-27 16:11 UTC, protos17 commented on Tracker/UI/Statistics/StatisticsViewController.swift
> +        UITableViewCell()
Ну ты тут даже ячейку для этой таблицы не сверстал :)

2023-11-27 16:11 UTC, protos17 commented on Tracker/UI/Trackers/TrackersViewController.swift
> +                    trackersView.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -10),
Константы для констрейнтов рекомендую выносить в extension класса: 

       extension TrackersViewController {     
          private enum Constants {         
            static let defaultOffset: CGFloat = 4    
                         ...           
              }      
          }

2023-11-27 16:11 UTC, protos17 commented on Tracker/UI/Trackers/TrackersViewModel.swift
> +            fatalError(error.localizedDescription)
Хочу отметить, что в продакшене не используется `fatalError`, кроме случаев, когда это необходимо, например, в банковском приложении при обнаружении джейлбрейка.
Лучше здесь показать ошибку

2023-11-27 16:11 UTC, protos17 commented on Tracker/UI/Trackers/TrackersViewModel.swift
> +            fatalError(error.localizedDescription)
Рекомендую убрать fatalError

2023-11-27 16:11 UTC, protos17 commented on Tracker/UI/Trackers/TrackersViewModel.swift
> +            fatalError(error.localizedDescription)
Рекомендую избавиться от него

2023-11-27 16:11 UTC, protos17 commented on Tracker/UI/Trackers/TrackersViewModel.swift
> +            fatalError(error.localizedDescription)
Лучше заменить хотя бы на assertionFailure

2023-11-27 16:11 UTC, protos17 commented on Tracker/UI/Trackers/TrackersViewModel.swift
> +            fatalError(error.localizedDescription)
Тут и ниже рекомендую избавиться от fatalError

2023-11-27 16:11 UTC, protos17 commented on Tracker/swiftgen.yml
Хоть здесь файл и отображается, в проекте он отсутствует. Возможно, при добавлении файла, ты не поставил галочку у addToTarget  и copy item if needed

2023-11-27 21:45 UTC, AndrewP-GH commented on Tracker/swiftgen.yml
да, рил, я думал надо только чтобы он был в ФС

2023-11-30 16:32 UTC, protos17 approved these changes

2023-11-30 16:32 UTC, protos17 commented on Tracker/UI/ConfigureTracker/CellWithValueProtocol.swift
> +    var wasSelected: Bool { get set }
Булевые переменные принято писать с приставкой is:

    isSelected: Bool

2023-11-30 16:32 UTC, protos17 commented on Tracker/UI/Filters/FiltersViewController.swift
> +                    filtersTable.topAnchor.constraint(equalTo: titleLabel.bottomAnchor, constant: 38),
Константы для констрейнтов рекомендую выносить в extension класса: 

       extension FiltersViewController { 
                  private enum Constants {       
                           static let defaultOffset: CGFloat = 4      
                                      ...           
          }        
       }

2023-11-30 16:32 UTC, protos17 commented on Tracker/UI/Statistics/StatisticsView.swift
> +                    titleLabel.heightAnchor.constraint(equalToConstant: 18),
Рекомендую все константы для констрейнтов выносить в константы класса

2023-11-30 16:32 UTC, protos17 commented on Tracker/UI/Trackers/TrackersViewModel.swift
> +            assertionFailure(error.localizedDescription)
Если чувствуешь в себе силы, попробуй реализовать отображение ошибок пользователю

2023-11-30 16:56 UTC, AndrewP-GH commented on Tracker/UI/ConfigureTracker/CellWithValueProtocol.swift
> +    var wasSelected: Bool { get set }
такое свойство уже есть у UICollectionViewCell, попробую сделать оверрайд

2023-11-30 17:26 UTC, merged